version: 2
updates:
  - package-ecosystem: npm
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/Berlin
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      npm-minor-patch:
        applies-to: version-updates
        update-types:
          - minor
          - patch
        patterns:
          - "*"
      npm-major:
        applies-to: version-updates
        update-types:
          - major
        patterns:
          - "*"

  - package-ecosystem: github-actions
    directory: "/"
    target-branch: main
    schedule:
      interval: weekly
      time: "05:00"
      timezone: Europe/Berlin
    commit-message:
      prefix: chore
      prefix-development: chore
      include: scope
    groups:
      github-actions-all:
        patterns:
          - "*"
